### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by luxigo** [Yousign/yousign-api-client-python#2]
Hello,

I have the problem below when trying to run examples/python_connection.py on Debian 8.

I dont know where to specify the SSL certificate (and I'm unsure I obtained the right certificate with "openssl s_client -showcerts -connect apidemo.yousign.fr:8181 </dev/null"  ) .

Could you help ? Thanks !
```text
/src/yousign-api-client-python/examples$ python connection.py 
Traceback (most recent call last):
  File "connection.py", line 9, in <module>
    c = ysApi.ApiClient('../config/config.ini')
  File "build/bdist.linux-x86_64/egg/ysApi/apiClient.py", line 82, in __init__
  File "build/bdist.linux-x86_64/egg/ysApi/apiClient.py", line 69, in createHeaders
  File "/usr/lib/python2.7/dist-packages/suds/client.py", line 112, in __init__
    self.wsdl = reader.open(url)
  File "/usr/lib/python2.7/dist-packages/suds/reader.py", line 152, in open
    d = self.fn(url, self.options)
  File "/usr/lib/python2.7/dist-packages/suds/wsdl.py", line 136, in __init__
    d = reader.open(url)
  File "/usr/lib/python2.7/dist-packages/suds/reader.py", line 79, in open
    d = self.download(url)
  File "/usr/lib/python2.7/dist-packages/suds/reader.py", line 95, in download
    fp = self.options.transport.open(Request(url))
  File "/usr/lib/python2.7/dist-packages/suds/transport/https.py", line 60, in open
    return  HttpTransport.open(self, request)
  File "/usr/lib/python2.7/dist-packages/suds/transport/http.py", line 62, in open
    return self.u2open(u2request)
  File "/usr/lib/python2.7/dist-packages/suds/transport/http.py", line 118, in u2open
    return url.open(u2request, timeout=tm)
  File "/usr/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:581)>
```

**Comment by luxigo** [comment]
Maybe this could help: http://thejosephturner.com/blog/post/https-certificate-verification-in-python-with-urllib2/

**Comment by ke20** [comment]
Hello,

The problem should be resolved now. 
We fixed the ssl problem on our server.

Sorry for my late reponse

**Comment by luxigo** [comment]
No prob, I've implemented it for nodejs in the meanwhile..
